Добавляет редакс
htmlacademy-react/1420381-six-cities-6 pull request #7
Opened 2021-02-24 17:13 UTC by rokeeCode

2021-02-24 18:07 UTC, Antoshka007 requested changes

2021-02-24 18:07 UTC, Antoshka007 commented on src/components/main-page/main-page.jsx
> +});
Задача `mapDispatchToProps` прокинуть экшенкриэйтор обёрнутый в dispatch. Обычно всё сводится к такому:
```js
import {bindActionCreators} from 'redux';

// ...

const mapDispatchToProps = (dispatch) => bindActionCreators({
  changeCity: ActionCreator.changeCity
}, dispatch);
```
Ссылка на доку: https://redux.js.org/api/bindactioncreators

2021-02-24 18:07 UTC, Antoshka007 commented on src/components/main-page/main-page.jsx
> +          <FilterBar onCityChange={onCityChange} currentCity={city}/>
Давай тут немного больше кода напишем, чтобы критерию [Д2](https://up.htmlacademy.ru/react/6/criteries#d2) соответствовать:
```suggestion
          <FilterBar onCityChange={handleCityChange} currentCity={city}/>
```
А выше в компоненте объявим эту функцию:
```js
const handleCityChange = (city) => onCityChange(city)
```

2021-02-24 20:55 UTC, Antoshka007 commented on src/components/main-page/main-page.jsx
> +});
Хотя вижу, что в академии показывают именно такой пример, как ты сделал. Меня пока смущает в таком подходе то, что бизнес-логика размазывается по нескольким местам. Но раз лекторы говорят так можно, не буду настаивать.

2021-02-25 17:39 UTC, rokeeCode commented on src/const.js
> +  paris: [48.8566969, 2.3514616],
-

2021-02-25 17:44 UTC, rokeeCode commented on src/components/main-page/main-page.jsx
> +});
-

2021-02-25 19:03 UTC, Antoshka007 requested changes
Почини страницу "Избранное", а в остальном ок 👌

2021-02-25 19:17 UTC, merged