Добавляет авторизацию.
htmlacademy-react/1420381-six-cities-6 pull request #9
Opened 2021-03-11 00:22 UTC by rokeeCode

2021-03-11 18:36 UTC, Antoshka007 requested changes
Отлично 👍
Отписал пару рекомендаций

2021-03-11 18:36 UTC, Antoshka007 commented on src/components/header/header.jsx
> +                <Link className="header__nav-link header__nav-link--profile" to={isAuthorized ? `/favorites` : `/login`}>
```suggestion
                <Link className="header__nav-link header__nav-link--profile" to={isAuthorized ? AppRoute.Favorites : AppRoute.Login}>
```

2021-03-11 18:36 UTC, Antoshka007 commented on src/components/header/header.jsx
> +  isUserInfoLoaded: state.isUserInfoLoaded
Не используется в компоненте

2021-03-11 18:36 UTC, Antoshka007 commented on src/components/private-route/private-route.jsx
> +  exact: PropTypes.bool.isRequired,
Почему isRequired?

2021-03-11 18:36 UTC, Antoshka007 commented on src/store/action.js
> +    type: ActionType.REQUIRED_AUTHORIZATION,
Может быть тут больше подойдёт
```suggestion
    type: ActionType.SET_AUTHORIZATION_STATUS,
```
?

2021-03-11 18:36 UTC, Antoshka007 commented on src/services/api.js
> +    throw err;
Это ведь получается необработанная ошибка.

2021-03-11 18:36 UTC, Antoshka007 commented on src/services/api.js
> +      throw err;
Можно так:
```suggestion
```

2021-03-11 18:36 UTC, Antoshka007 commented on src/store/api-actions.js
> +  api.get(`/comments/${id}`)
Давай тут тоже через ApiRoute сделаем

2021-03-11 19:15 UTC, rokeeCode commented on src/const.js
> +  OfferPage: `/offer`,
??

2021-03-12 07:58 UTC, Antoshka007 commented on src/const.js
> +  OfferPage: `/offer`,
Ну у тебя же нет страницы `/offer`. Есть страница `/offer/:id`.

2021-03-12 18:56 UTC, merged